---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: test-apache
    box: centos/7
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../../inventories/apache
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
